- server/.gitignore
- server/drizzle.config.ts
- server/package.json
- server/src/app.ts
- server/src/db/index.ts
- server/src/db/schema.ts
- server/src/index.ts
#16 
로그인 API 구현
계정생성 API 구현
비밀번호 해시화
> feature : login_API

- client/src/components/LetterCreate/LetterInfoForm.js
- client/src/components/LetterCreate/YearMonthDayPicker.js
- client/src/pages/LetterCreatePage.js
#22 
- 서버에 현재 편지 전송 시각과 설정한 편지 수신 년도, 날짜, 시각의 UNIX 타임스탬프 구현
> [Client] feature/#22 편지 발신 및 수신 시각 UNIX 타임스탬프 구현

- server/src/app.ts
Fixes #30 
Use status code in account API
> refactor: make use status code in account API

- server/src/app.ts
Fixes #30 
login에 400을 출력하는 코드가 빠져있어 추가합니다.
> refactor: use status code in API 2

- server/src/app.ts
#30
400을 출력하는 코드에서 send를 안해 루프가 걸려서, send를 추가
> fix: loop in 400 in #30

- server/package.json
- server/pnpm-lock.yaml
- server/src/app.ts
> feature: add cors for localhost:3000

- client/src/App.js
- client/src/components/Header.js
- client/src/components/LetterCreate/LetterFloatingButton.js
- client/src/components/LetterCreate/LetterInputForm.js
- client/src/components/LetterCreate/PrivacySelector.js
- client/src/components/LetterCreate/YearMonthDayPicker.js
- client/src/components/MyPage/MyPage.js
- client/src/components/app/Router.js
- client/src/index.js
- client/src/pages/LetterCreatePage.js
#42
Netlify 프론트 배포 에러 해결을 위해서 사용하지 않는 변수 제거
> [Client] fix: 프론트엔드 배포 에러 해결

- server/.oxlintrc.json
- server/package.json
- server/pnpm-lock.yaml
- server/src/app.ts
- server/src/jwt/jwt.ts
- server/src/main.ts
- server/tsdown.config.ts
> [server] init tsdown for faster build

- server/src/app.ts
> [server] fix: add_allowlist

- server/src/app.ts
- server/src/main.ts
> [server] feature: allow to include credentials

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/components/Header.js
- client/src/components/Login/LoginPage.css
- client/src/components/Login/LoginPage.js
- client/src/components/app/Router.js
- client/src/components/test.js
- client/src/context/AuthContext.js
- client/src/index.js
- client/src/pages/JoinPage.js
#55
- 서버와의 api
- 헤더에 token 정보가 자동으로 저장되도록 구현
> [Client] feature: 로그인 기능 구현

- client/.env
- client/public/_redirects
- client/src/components/Login/LoginPage.js
- client/src/components/test.js
- client/src/pages/JoinPage.js
> [Client] fix: HTTP/HTTPS 배포 에러 해결

- client/src/components/test.js
- client/src/index.js
#61 
- Netlify 배포 에러 해결을 위해 사용하지 않는 변수 제거
> [Client] fix : 사용하지 않는 변수 제거

- client/src/assets/Join/Join.module.css
- client/src/components/Header.js
- client/src/components/LetterCreate/LetterInfoForm.js
- client/src/components/Login/LoginPage.css
- client/src/components/Login/LoginPage.js
- client/src/components/app/Router.js
- client/src/pages/JoinPage.js
#63 
- 로그인/ 회원가입 폼에서 유효성 검사 추가
> [Client] feature: 회원가입 입력 폼 비밀번호 보기 버튼 생성

- client/src/components/LetterCreate/LetterInfoForm.js
- client/src/components/test.js
- client/src/pages/LetterCreatePage.js
#66
토큰을 이용하여 사용자 id 자동 설정
토큰을 이용하여 체크박스 체크 시 작성자가 가입한 이메일로 자동 설정
> [Client] feature: 사용자 정보 가져오기

- server/package.json
- server/pnpm-lock.yaml
- server/src/app.ts
- server/src/db/index.ts
- server/tsconfig.json
> [server] implement letter api

- client/src/assets/LetterCreate/LetterCreatePage.module.css
- client/src/assets/LetterCreate/LetterInfoForm.module.css
- client/src/components/MyPage/MyPage.js
- client/src/components/app/Router.js
- client/src/components/test.js
- client/src/pages/LetterCreatePage.js
#73 
- 편지 생성 api 연동
- 편지 정보 저장 폼의 CSS 디바이스 맞게 적용되도록 변경
> [Client] feature: 편지 생성 API 연동

- client/package.json
> [Client] chore: package.json 의존성 추가 

- client/src/components/MyPage/MyPage.js
> [Client] fix :  사용하지 않는 변수 제거

- server/public/index.html
- server/src/app.ts
Fixes #82
add index.html for server.slowpost.p-e.kr
> [Server] add index.html

- server/src/app.ts
#82 
fix path error in loading index.html
> [Server] fix: path error in loading index.html in server

- server/src/app.ts
#82
cannot serve index.html -> write directly on server -> commit to reflect the repo
> fix: serve index.html with debug in production

- client/src/pages/MainPage.js
#88
배포 에러 해결을 위하 img 태그에 alt 요소 추가
> [Client] fix : 배포 에러 해결

- client/src/components/Header.js
> [Client] fix : 로그인 정보 전역 관리 적용
